### ISSUE TITLE
Squilly Boat Glitch does not work with the ender relay

### ISSUE THREAD

**Issue by MaximumG9** [xyzeva/ender-relay#1]
When respawning in a space that is taken up by a solid entity hitbox (ex. shulker or boat) you're repeatedly moved upwards by one block until you reach a place with enough space to spawn. This does not happen when warping with the ender relay as it was described that it would in [Kenadian's video](https://youtu.be/L1i4izl25V4?t=415).

**Comment by MaximumG9** [comment]
The ender relay is also inconsistent with the beds and respawn anchor in what spots are obstructed. The bed and respawn anchor allow you to spawn within a space that your hitbox would fit it (ex. 1 block tall spaces when crawling). But the current implementation of the ender relay does not work like this.

**Comment by xyzeva** [comment]
I have no idea on what causes this. As the teleport code literally uses the exact same thing as the respawn anchor.
